feat: add recipe details component
zaidi-01/PantryPal pull request #33
Opened 2023-11-18 08:23 UTC by StevieShibly8

- Add /api/ route to api calls
- Add recipe details component
- Add recipe details controller that gets recipe data from the database
- Add Recipe and Ingredient data classes
- Add DbSet for Recipe and Ingredient classes to ApplicationDbContext

2023-11-18 08:33 UTC, NilinReza approved these changes
Hope it works! :)

2023-11-18 09:24 UTC, zaidi-01 requested changes

2023-11-18 09:24 UTC, zaidi-01 commented on client/src/app/app.module.ts
> +      { path: 'recipe-details', component: RecipeDetailsComponent },
Just `recipe` fits better, `recipe/{recipe_id}`.

2023-11-18 09:24 UTC, zaidi-01 commented on client/src/app/recipe-details/recipe-details.component.ts
> +        http.get<RecipeDetails>(baseUrl + 'api/recipedetails').subscribe(result => {
Move this call to `RecipeService`. For example, `recipeService.get(recipeId)`.

2023-11-18 09:24 UTC, zaidi-01 commented on client/src/app/recipe-details/recipe-details.component.ts
> +interface RecipeDetails {
Just `Recipe` is good, it more or less means the same thing but fits better. Also, move this to the `RecipeService` or within that same directory, `client/src/services/recipe`.

2023-11-18 09:24 UTC, zaidi-01 commented on server/Controllers/RecipeDetailsController.cs
> +    public async Task<IActionResult> Test()
All of this should go under the `RecipeController`. "Details" are a subsection of recipes, much like searching, adding and deleting.

2023-11-18 09:24 UTC, zaidi-01 commented on server/Models/Recipe.cs
> +        public string? Cook_Time { get; set; }
TODO: figure out how to map these values properly. If nothing works then we'll rename the database columns.

2023-11-18 09:24 UTC, zaidi-01 commented on client/src/app/recipe-details/recipe-details.component.css
> +:host {
Make this an `scss` file.

2023-11-18 09:24 UTC, zaidi-01 commented on client/src/app/recipe-details/recipe-details.component.ts
> +export class RecipeDetailsComponent {
Add the spec file as well.

2023-11-19 01:57 UTC, NilinReza approved these changes
No PRs during weekend please! :)

2023-11-19 02:00 UTC, zaidi-01 approved these changes

2023-11-19 02:05 UTC, JJTomines approved these changes

2023-11-19 02:06 UTC, merged